# Generated by Django 4.2.6 on 2023-11-27 16:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produtos do Pedido',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[['pendente', 'Pendente'], ['finalizado', 'Finalizado']], default='pendente', max_length=255)),
                ('products', models.ManyToManyField(blank=True, to='order.productorder', verbose_name='Produtos')),
            ],
            options={
                'verbose_name': 'Pedido',
            },
        ),
    ]
