# Generated by Django 4.2.6 on 2023-10-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido'},
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'verbose_name': 'Produtos do Pedido'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[['Pendente', 'pendente'], ['Finalizado', 'finalizado']], default='Pendente', max_length=255),
        ),
    ]
