# Generated by Django 4.2.6 on 2023-10-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_alter_productorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[['Pendente', 'pendente'], ['Finalizado', 'finalizado']], default='pendente', max_length=255),
        ),
    ]
