# Generated by Django 4.2.6 on 2023-10-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_client_alter_order_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.TimeField(auto_created=True, blank=True, null=True),
        ),
    ]
