# Generated by Django 4.2.6 on 2023-10-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='order.productorder', verbose_name='Produtos'),
        ),
    ]
